### READ all user(req to protected route)
GET http://localhost:4000/user-api/users
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlcmlAZ21haWwuY29tIiwiaWF0IjoxNzcyODc3MTg2LCJleHAiOjE3NzI4ODA3ODZ9.1Ngwu6J4KjKXVPXeNtHE9c5B1tc16iqEW5w-NFdOau8; Path=/; HttpOnly; SameSite=Lax


### READ a user by id
GET http://localhost:4000/user-api/users/69aaa103a47b0e01f8bd9adb

### CREATE new user
POST http://localhost:4000/user-api/users
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlcmlAZ21haWwuY29tIiwiaWF0IjoxNzcyODc3MTg2LCJleHAiOjE3NzI4ODA3ODZ9.1Ngwu6J4KjKXVPXeNtHE9c5B1tc16iqEW5w-NFdOau8; Path=/; HttpOnly; SameSite=Lax

Content-Type: application/json

{
  
  "password":"895623",
  "email":"peri@gmail.com",
  "username":"lol155"
  

}

###
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
  
  "password":"895623",
  "email":"peri@gmail.com"

}



 
### UPDATE a user
PUT http://localhost:4000/user-api/users/69abf57c75a27a48c1c8c504
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBlcmlAZ21haWwuY29tIiwiaWF0IjoxNzcyODc3MTg2LCJleHAiOjE3NzI4ODA3ODZ9.1Ngwu6J4KjKXVPXeNtHE9c5B1tc16iqEW5w-NFdOau8; Path=/; HttpOnly; SameSite=Lax
Content-Type: application/json

{
    
    "password":"878789",
    "email":"cuvve@gmail.com",
    "username":"mkmkmm"
    
    
}


### DELETE a user
DELETE http://localhost:4000/user-api/users/69abbdbd5209864e011be2c5
// it dont support the body

