### READ all product
GET http://localhost:5353/products
// dont support thee body

### READ a product by Brand
GET http://localhost:5353/products/puma

### CREATE new product
POST http://localhost:5353/products
Content-Type: application/json

{
    "id":1101,
    "name":"shoes",
    "Brand":"puma",
    "price":45000
}

 
### UPDATE a product
PUT http://localhost:5353/products
Content-Type: application/json

{
    "id":1101,
    "name":"shirt",
    "Brand":"nike",
    "price":60000
}

### DELETE a product
DELETE http://localhost:5353/products/1104
// it dont support the body


// post request and put req should send 
// get and delete requests donot support bod of the request object. so that these two request can send the data through end point